### ISSUE TITLE
cannot bundle install with 'https://ruby.taobao.org'

### ISSUE THREAD

**Issue by wanming** [huaoguo/fuck-redis#1]
`Could not verify the SSL certificate for
https://rubygems-china.oss.aliyuncs.com/quick/Marshal.4.8/sinatra-contrib-1.4.2.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle
attack, but most likely your system doesn't have the CA
certificates needed for verification. For information about
OpenSSL certificates, see bit.ly/ruby-ssl. To connect
without using SSL, edit your Gemfile sources and change
'https' to 'http'.`

IT WORKS LIKE CHARM AFTER I CHANGE `HTTPS' TO 'HTTP'.

**Comment by huaoguo** [comment]
interesting

**Comment by wanming** [comment]
不改自杀

**Comment by huaoguo** [comment]
您好，已解决了您的问题，欢迎您对本项目的关注。
